apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  annotations:
    run.googleapis.com/creator: indrakenyadevelopment@gmail.com
    run.googleapis.com/lastModifier: indrakenyadevelopment@gmail.com
  labels:
    cloud.googleapis.com/location: europe-west1
    run.googleapis.com/lastUpdatedTime: '2026-07-19T13:57:22.344359Z'
  name: sales-scraper
  namespace: '693887939589'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 572.0.0
        run.googleapis.com/execution-environment: gen2
      labels:
        client.knative.dev/nonce: suf_fax_has
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - env:
            - name: POSTGRES_HOST
              value: aws-0-eu-west-1.pooler.supabase.com
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres.agwjduiekszcreehnhyz
            - name: PGSSLMODE
              value: require
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: sales-db-url
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: sales-db-password
            image: europe-west1-docker.pkg.dev/sales-intelligens/sales-intelligence/worker:c0f44f2
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
          maxRetries: 1
          serviceAccountName: sales-worker@sales-intelligens.iam.gserviceaccount.com
          timeoutSeconds: '900'
